# Generated by Django 3.0.7 on 2020-08-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactuspage',
            old_name='url_embedded_maps',
            new_name='HTML_embedded_maps',
        ),
    ]
