# Generated by Django 3.0.7 on 2020-08-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20200809_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormConfirmEmail',
            new_name='ContactUsConfirmEmail',
        ),
    ]
