# Generated by Django 3.0.9 on 2020-08-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20200811_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuspage',
            name='HTML_embedded_maps',
            field=models.CharField(blank=True, max_length=511),
        ),
    ]
