# Generated by Django 3.0.9 on 2020-08-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_auto_20200815_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactuspage',
            old_name='HTML_embedded_maps',
            new_name='html_embedded_maps',
        ),
    ]
