# Generated by Django 3.0.9 on 2020-08-18 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpage',
            name='date_display',
            field=models.DateField(default=datetime.date.today, verbose_name='Publish date'),
        ),
    ]
