# Generated by Django 3.0.9 on 2020-08-18 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20200818_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpage',
            name='date_display',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish date'),
        ),
    ]
