# Generated by Django 3.0.7 on 2020-08-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('telephone_number', models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 62215678901", verbose_name='Telephone Number')),
                ('handphone_number', models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 6281234567890", verbose_name='Handphone / WhatsApp Number')),
                ('address', models.CharField(blank=True, max_length=511, verbose_name='Address')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
