# Generated by Django 3.0.9 on 2020-08-19 12:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('navigation_links', wagtail.core.fields.StreamField([('NonDropdown', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('page', wagtail.core.blocks.PageChooserBlock())])), ('Dropdown', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('sub_links', wagtail.core.blocks.StreamBlock([('SubLink', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('page', wagtail.core.blocks.PageChooserBlock())]))]))]))], blank=True)),
            ],
            options={
                'verbose_name': 'Navigation Bar',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('telephone_number', models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 62215678901", null=True, verbose_name='Telephone Number')),
                ('handphone_number_1', models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 6281234567890", null=True, verbose_name='Handphone / WhatsApp Number 1')),
                ('handphone_number_2', models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 6281234567890", null=True, verbose_name='Handphone / WhatsApp Number 2')),
                ('address', models.CharField(blank=True, max_length=511, verbose_name='Address')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
