# Generated by Django 3.0.9 on 2020-08-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='copyright_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
