# Generated by Django 3.0.7 on 2020-08-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200809_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alamat',
            field=models.CharField(blank=True, max_length=511, verbose_name='Alamat'),
        ),
    ]
