# Generated by Django 3.0.9 on 2020-09-03 15:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_seodefault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='navigation_links',
            field=wagtail.core.fields.StreamField([('NonDropdown', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='External URL will be prioritized over page link', required=False))])), ('Dropdown', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('sub_links', wagtail.core.blocks.StreamBlock([('SubLink', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='External URL will be prioritized over page link', required=False))]))]))]))], blank=True),
        ),
    ]
