# Generated by Django 3.0.7 on 2020-08-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_profile_handphone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='handphone_number',
            field=models.BigIntegerField(blank=True, default=0, help_text="Don't forget with country code. Example: 6281234567890", verbose_name='Handphone / WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone_number',
            field=models.BigIntegerField(blank=True, default=0, help_text="Don't forget with country code. Example: 62215678901", verbose_name='Telephone Number'),
        ),
    ]
