# Generated by Django 3.0.7 on 2020-08-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('coderedcms', '0018_auto_20200805_1702'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('website', '0003_profile_alamat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='coderedpage_ptr',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='thank_you_page',
        ),
        migrations.RemoveField(
            model_name='formpagefield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='coderedpage_ptr',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='alamat',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=511, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='handphone_number',
            field=models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 6281234567890", verbose_name='Handphone / WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone_number',
            field=models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 62215678901", verbose_name='Telephone Number'),
        ),
        migrations.DeleteModel(
            name='FormConfirmEmail',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
        migrations.DeleteModel(
            name='FormPageField',
        ),
        migrations.DeleteModel(
            name='WebPage',
        ),
    ]
