# Generated by Django 3.0.7 on 2020-08-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200811_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='handphone_number',
            field=models.CharField(blank=True, help_text="Don't forget with country code. Example: 6281234567890", max_length=25, verbose_name='Handphone / WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone_number',
            field=models.CharField(blank=True, help_text="Don't forget with country code. Example: 62215678901", max_length=25, verbose_name='Telephone Number'),
        ),
    ]
