# Generated by Django 3.0.7 on 2020-08-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200811_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='handphone_number',
            field=models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 6281234567890", null=True, verbose_name='Handphone / WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone_number',
            field=models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 62215678901", null=True, verbose_name='Telephone Number'),
        ),
    ]
