# Generated by Django 3.0.9 on 2020-08-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200811_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telephone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone_number_1',
            field=models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 62215678901", null=True, verbose_name='Telephone Number 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone_number_2',
            field=models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 62215678901", null=True, verbose_name='Telephone Number 2'),
        ),
    ]
