# Generated by Django 3.0.9 on 2020-08-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200814_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='handphone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telephone_number_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telephone_number_2',
        ),
        migrations.AddField(
            model_name='profile',
            name='handphone_number_1',
            field=models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 6281234567890", null=True, verbose_name='Handphone / WhatsApp Number 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='handphone_number_2',
            field=models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 6281234567890", null=True, verbose_name='Handphone / WhatsApp Number 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone_number',
            field=models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 62215678901", null=True, verbose_name='Telephone Number'),
        ),
    ]
