# Generated by Django 3.0.9 on 2020-08-15 08:59

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation_links', wagtail.core.fields.StreamField([('NonDropdown', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('page', wagtail.core.blocks.PageChooserBlock())])), ('Dropdown', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('sub_links', wagtail.core.blocks.StreamBlock([('PageLink', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('page', wagtail.core.blocks.PageChooserBlock())]))], required=True))]))], blank=True)),
            ],
            options={
                'verbose_name': 'Navigation Bar',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
