# Generated by Django 3.0.9 on 2020-08-15 09:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200815_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='navigation_links',
            field=wagtail.core.fields.StreamField([('NonDropdown', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('page', wagtail.core.blocks.PageChooserBlock())]))], blank=True),
        ),
    ]
