# Generated by Django 3.0.9 on 2020-08-15 10:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200815_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='navigation_links',
            field=wagtail.core.fields.StreamField([('NonDropdown', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('page', wagtail.core.blocks.PageChooserBlock())])), ('Dropdown', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('sub_links', wagtail.core.blocks.StreamBlock([('SubLink', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(max_length=255)), ('page', wagtail.core.blocks.PageChooserBlock())]))], required=True))]))], blank=True),
        ),
    ]
