# Generated by Django 3.0.9 on 2020-08-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200818_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
