# Generated by Django 3.0.8 on 2020-07-19 12:29

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_remove_articlepage_coba"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="coba",
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
