# Generated by Django 3.1.6 on 2021-02-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('website', '0003_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('telephone_number', models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 62215678901", null=True, verbose_name='Telephone Number')),
                ('handphone_number_1', models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 6281234567890", null=True, verbose_name='Handphone / WhatsApp Number 1')),
                ('handphone_number_2', models.BigIntegerField(blank=True, help_text="Don't forget with country code. Example: 6281234567890", null=True, verbose_name='Handphone / WhatsApp Number 2')),
                ('copyright_year', models.IntegerField(blank=True, null=True, verbose_name='Copyright Year')),
                ('address', models.CharField(blank=True, max_length=511, verbose_name='Address')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
