# Generated by Django 3.1.6 on 2021-02-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('coderedcms', '0019_spelling_corrections'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('website', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='coderedpage_ptr',
        ),
        migrations.DeleteModel(
            name='ArticleIndexPage',
        ),
        migrations.DeleteModel(
            name='ArticlePage',
        ),
    ]
