# Generated by Django 3.0.9 on 2020-08-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopage',
            old_name='link_thumbnail_embed_video',
            new_name='link_youtubeo',
        ),
    ]
