# Generated by Django 3.0.8 on 2020-07-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
