# Generated by Django 3.0.9 on 2020-08-18 04:13

import datetime
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='end_time_each_day',
            field=models.TimeField(blank=True, default=datetime.time(16, 0), null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='location',
            field=models.CharField(blank=True, default='Insan-Q Cilegon', max_length=1023),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='long_description',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_time_each_day',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
    ]
