# Generated by Django 3.0.7 on 2020-08-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0018_auto_20200805_1702'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('coderedpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coderedcms.CoderedPage')),
                ('hits', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Event Landing Page',
            },
            bases=('coderedcms.coderedpage',),
        ),
    ]
