# Generated by Django 3.0.7 on 2020-08-09 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200809_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='end_time_each_day',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='location',
            field=models.CharField(default='Insan-Q Cilegon', max_length=511),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='start_time_each_day',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='wednesday',
            field=models.BooleanField(default=True),
        ),
    ]
