# Generated by Django 3.0.9 on 2020-08-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200818_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='friday',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='monday',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='saturday',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='sunday',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='thursday',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='tuesday',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='wednesday',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
