# Generated by Django 3.0.7 on 2020-08-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0018_auto_20200805_1702'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('event', '0003_auto_20200809_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='coderedpage_ptr',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='thank_you_page',
        ),
        migrations.RemoveField(
            model_name='eventpagefield',
            name='page',
        ),
        migrations.DeleteModel(
            name='EventConfirmEmail',
        ),
        migrations.DeleteModel(
            name='EventPage',
        ),
        migrations.DeleteModel(
            name='EventPageField',
        ),
    ]
