# Generated by Django 3.0.9 on 2020-08-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_company_name',
            field=models.CharField(max_length=255),
        ),
    ]
