# Generated by Django 3.0.9 on 2020-08-09 07:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='section_layanan_kami',
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_layanan',
            field=wagtail.core.fields.StreamField([('Layanan', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.RichTextBlock()), ('thumbnail', wagtail.images.blocks.ImageChooserBlock())]))], blank=True),
        ),
    ]
