# Generated by Django 3.0.9 on 2020-08-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='landing_articles_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='landing_events_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
