# Generated by Django 3.0.9 on 2020-08-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200809_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagegalleryimage',
            name='caption',
        ),
    ]
