# Generated by Django 3.0.7 on 2020-08-11 14:52

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200811_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='layanan_layanan',
            new_name='section_layanan',
        ),
        migrations.AlterField(
            model_name='homepagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_images', to='home.HomePage'),
        ),
    ]
