# Generated by Django 3.0.7 on 2020-08-11 15:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagegalleryimage_related_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagegalleryimage',
            name='related_page',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_layanan',
            field=wagtail.core.fields.StreamField([('Layanan', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.RichTextBlock()), ('thumbnail', wagtail.images.blocks.ImageChooserBlock()), ('panels', wagtail.core.blocks.PageChooserBlock(required=False))]))], blank=True),
        ),
    ]
