# Generated by Django 3.0.7 on 2020-08-11 16:16

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200811_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hits',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_layanan',
            field=wagtail.core.fields.StreamField([('Layanan', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.RichTextBlock()), ('thumbnail', wagtail.images.blocks.ImageChooserBlock()), ('related_page', wagtail.core.blocks.PageChooserBlock(required=False))]))], blank=True),
        ),
    ]
