# Generated by Django 3.0.9 on 2020-08-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0006_auto_20200811_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagegalleryimage',
            name='page',
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_company_name',
            field=models.CharField(default='coba', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_description',
            field=models.CharField(blank=True, max_length=511),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
