# Generated by Django 3.0.9 on 2020-08-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200815_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
