# Generated by Django 3.0.9 on 2020-08-15 08:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200815_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='section_layanan',
            field=wagtail.core.fields.StreamField([('Layanan', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtail.core.blocks.RichTextBlock()), ('thumbnail', wagtail.images.blocks.ImageChooserBlock()), ('related_page', wagtail.core.blocks.PageChooserBlock(required=False))]))], blank=True),
        ),
    ]
