# Generated by Django 3.0.9 on 2020-08-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0009_auto_20200815_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='recent_articles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
