# Generated by Django 3.0.9 on 2020-08-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200814_1711'),
        ('home', '0010_homepage_recent_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='recent_articles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='article.ArticleIndexPage'),
        ),
    ]
