# Generated by Django 3.0.9 on 2020-08-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('home', '0011_auto_20200815_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='recent_articles',
            new_name='landing_articles',
        ),
        migrations.AddField(
            model_name='homepage',
            name='landing_events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.EventIndexPage'),
        ),
    ]
