# Generated by Django 3.0.9 on 2020-08-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200816_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageGalleryImage',
        ),
    ]
