# Generated by Django 3.0.9 on 2020-08-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('article', '0005_auto_20200816_1720'),
        ('home', '0013_delete_homepagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='landing_articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='article.ArticleIndexPage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='landing_events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.EventIndexPage'),
        ),
    ]
