# Generated by Django 3.0.9 on 2020-08-18 06:34

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200816_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_description',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_layanan',
            field=wagtail.core.fields.StreamField([('Layanan', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('thumbnail', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.core.blocks.RichTextBlock(required=False)), ('related_page', wagtail.core.blocks.PageChooserBlock(required=False))]))], blank=True),
        ),
    ]
