# Generated by Django 3.0.9 on 2020-08-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindexpage',
            name='is_company_articles',
            field=models.BooleanField(default=False, help_text='Company articles adalah artikel-artikel mengenai Insanq. Misal: Konseling, Test Psikologi, Seminar & Training', verbose_name='Is this company articles?'),
        ),
    ]
