# Generated by Django 3.0.9 on 2020-08-09 05:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
