# Generated by Django 3.0.9 on 2020-08-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'ordering': ['-first_published_at'], 'verbose_name': 'Article Page'},
        ),
    ]
