# Generated by Django 3.0.9 on 2020-08-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200814_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexpage',
            name='is_company_articles',
            field=models.BooleanField(default=False, verbose_name='Is this company articles?'),
        ),
    ]
