# Generated by Django 3.0.9 on 2020-08-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articleindexpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleindexpage',
            name='body',
        ),
    ]
