# Generated by Django 3.0.9 on 2020-08-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('article', '0003_articleindexpage_is_company_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
