# Generated by Django 3.0.9 on 2020-08-09 05:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200809_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='manca',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, default='haloo'),
            preserve_default=False,
        ),
    ]
