# Generated by Django 3.0.9 on 2020-08-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200809_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=models.CharField(max_length=100),
        ),
    ]
