# Generated by Django 3.0.9 on 2020-08-16 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200816_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='date_display',
            field=models.DateField(default=datetime.date.today, verbose_name='Publish date'),
        ),
    ]
