# Generated by Django 3.0.9 on 2020-08-09 06:02

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200809_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='body',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='body_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='body'),
        ),
    ]
