# Generated by Django 3.0.9 on 2020-08-18 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200816_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='date_display',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish date'),
        ),
    ]
