# Generated by Django 3.0.9 on 2020-08-09 06:42

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200809_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body_text',
            field=wagtail.core.fields.RichTextField(verbose_name='body'),
        ),
    ]
