# Generated by Django 3.0.13 on 2021-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_description',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='landing_events_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
