# Generated by Django 3.0.13 on 2021-03-21 13:45

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='long_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
