# Generated by Django 3.0.13 on 2021-03-21 13:48

from django.db import migrations, models
import webapps.apps.event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210321_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='location',
            field=models.CharField(blank=True, default='LiniMuda', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='to_address',
            field=models.CharField(blank=True, default=webapps.apps.event.models.get_email, help_text='Optional - email form submissions to this address. Separate multiple addresses by comma.', max_length=255, null=True, verbose_name='Email form submissions to'),
        ),
    ]
